# Configuration file for Bonded CLI Tool

# API Configuration
api:
  openrouter:
    base_url: "https://openrouter.ai/api/v1"
    model: "meta-llama/llama-3.1-8b-instruct:free"
    max_tokens: 1000
    temperature: 0.7
  
  openai:
    model: "gpt-4"
    max_tokens: 4000
    temperature: 0.7

# Rate Limiting
rate_limiting:
  requests_per_minute: 100
  max_concurrent: 5
  retry_attempts: 3
  retry_delay: 1.0

# Quality Control Settings
quality_control:
  min_word_count: 800
  min_score_threshold: 70
  
  # Check weights (must sum to 100)
  check_weights:
    word_count: 15
    seo_optimization: 15
    eeat_signals: 15
    structure: 15
    readability: 15
    faq_section: 10
    keyword_integration: 10
    grammar_quality: 5

# Content Generation Settings
content:
  expand_if_below_minimum: true
  include_faq: true
  min_faq_questions: 3
  target_audience_integration: true

# Output Settings
output:
  csv_encoding: "utf-8"
  json_indent: 2
  include_timestamps: true